sudo: false
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
  - '11'
env:
  - AGENT_VERSION=2
  - AGENT_VERSION=3
  - AGENT_VERSION=4
matrix:
  exclude:
    - node_js: '4'
      env: AGENT_VERSION=2
    - node_js: '4'
      env: AGENT_VERSION=4
    - node_js: '6'
      env: AGENT_VERSION=2
    - node_js: '6'
      env: AGENT_VERSION=4
    - node_js: '8'
      env: AGENT_VERSION=2
    - node_js: '10'
      env: AGENT_VERSION=2
    - node_js: '11'
      env: AGENT_VERSION=2
    - node_js: '11'
      env: AGENT_VERSION=3
before_install:
  - sed -i.bak '/"agentkeepalive":/d' package.json
script:
  - eval "npm i agentkeepalive@$AGENT_VERSION"
  - npm run ci
after_script:
  - npm i codecov && codecov
